import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "@/components/ui/toaster";
import { QueryClientProvider } from "@/providers";
// fr-FR locale is imported as frFR
import { viVN } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";
const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider localization={viVN}>
			<html lang="en" suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<Toaster />
					<QueryClientProvider>{children}</QueryClientProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
