import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<SidebarProvider>
			<AppSidebar />
			<main className="flex flex-col w-full">
				<SidebarTrigger />
				<div className="flex-1 rounded-lg p-3 m-3 bg-gray-50">
					{children}
				</div>
			</main>
		</SidebarProvider>
	);
}
