import { AppSidebar } from "@/components/ui/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import type { Metadata } from "next";
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className="max-w-screen overflow-hidden">
			<SidebarProvider>
				<AppSidebar />
				<main className="flex flex-col overflow-auto w-full">
					<SidebarTrigger />
					<div className="flex-1 w-full  rounded-lg p-3  bg-slate-50 overflow-auto ">
						{children}
					</div>
				</main>
			</SidebarProvider>
		</div>
	);
}
